name: Rust Test Coverage

on: [push]

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests and Generate Coverage Report
        run: cargo install cargo-tarpaulin && cargo tarpaulin --all-features --ignore-tests

      - name: Extract Coverage Percentage
        run: |
          COVERAGE_THRESHOLD=85
          ACTUAL_COVERAGE=$(grep -oP "(?<=^Overall coverage rate: )[0-9.]+" target/debug/tarpaulin/cobertura/coverage.xml)
          if (( $(bc <<< "$ACTUAL_COVERAGE >= $COVERAGE_THRESHOLD") )); then
            echo "Coverage is above or equal to $COVERAGE_THRESHOLD%"
          else
            echo "Coverage is below $COVERAGE_THRESHOLD%"
            exit 1
          fi
