name: Rust Test and Coverage

on: [push]

jobs:
  test-and-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run tests
        run: cargo tarpaulin

      - name: Check coverage percentage
        run: ./.github/workflows/scripts/check-coverage.sh
