# 1. Execute on push
on: [push]

jobs:
  ut_check:
    # 2. Run on latest Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 3. Checkout repository
      - uses: actions/checkout@v3

      - name: Install grcov
      # 4. Install grcov
        run: cargo install grcov

      # - name: Run tests
      # 5. Run run_tests.sh
      #  run: ./.github/workflows/scripts/run_tests.sh

      - name: Check coverage
      # 6. Run check_coverage.sh
        run: ./.github/workflows/scripts/check_coverage.sh
