name: Rust Test and Coverage

on: [push]

jobs:
  test-and-coverage:
    name: Check Unit Test Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Check coverage percentage
        run: ./.github/workflows/scripts/check_coverage.sh
